### ISSUE TITLE
请问大佬前端代理应该怎么设置呢

### ISSUE THREAD

**Issue by soyoyecuaemf** [2331892928/AMEN-GoEdge-User_frontEnd#1]
现在宝塔反代后打开页面报404。

反代Nginx配置

#PROXY-START/

location /api
{
    proxy_pass http://127.0.0.1:20222/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_http_version 1.1;
    # proxy_hide_header Upgrade;

    add_header X-Cache $upstream_cache_status;
    #Set Nginx Cache

    set $static_fileOUdlDpBp 0;
    if ( $uri ~* "\.(gif|png|jpg|css|js|woff|woff2)$" )
    {
        set $static_fileOUdlDpBp 1;
        expires 1m;
    }
    if ( $static_fileOUdlDpBp = 0 )
    {
        add_header Cache-Control no-cache;
    }
}
#PROXY-END/

前端vue.config.js改动部分
module.exports = {
  lintOnSave: false,
  // publicPath: process.env.NODE_ENV === 'production' ? '/vue-quasar-manage/' : '/',
  // publicPath: '/',
  devServer: {
    disableHostCheck: true,
    host: 'localhost',
    port: 20224,
    proxy: {
      '/api': {
        target: 'http://xxxxx.xxxx.xx:20222', // localhost:8080
        changeOrigin: true,
        pathRewrite: {
          '^/api': ''
        }
      }
    }
  },

请问是哪配置错了呢

**Comment by 2331892928** [comment]
你的反向代理可能没有问题，有问题的是你的后端

**Comment by 2331892928** [comment]
不对，代理为/api/，不是/api，你的是/api
