### ISSUE TITLE
里面链接没了

### ISSUE THREAD

**Issue by skyhhjmk** [2331892928/AMEN-GoEdge-User_frontEnd#3]
![image](https://github.com/2331892928/AMEN-GoEdge-User_frontEnd/assets/78078552/9d88739b-3dc9-4de2-a5ef-3b6ee1d46132)

http 403

**Comment by 2331892928** [comment]
这是哪个模块的内容

**Comment by skyhhjmk** [comment]
![image](https://github.com/2331892928/AMEN-GoEdge-User_frontEnd/assets/78078552/0cdd9f6e-6059-49f7-826f-76bcb6123dff)
前端

**Comment by skyhhjmk** [comment]
![image](https://github.com/2331892928/AMEN-GoEdge-User_frontEnd/assets/78078552/ab80d592-e9dd-4060-8a4e-3fd86cef6d8c)

**Comment by 2331892928** [comment]
这并不会影响登录效果，这个链接很早以前就403了，你可以忽略，登录页面那个小块会一直显示加载中，但加载不出来，这并不影响

**Comment by skyhhjmk** [comment]
跪求大佬修一下

**Comment by skyhhjmk** [comment]
啊我悟了
