### ISSUE TITLE
请求后端时405错误

### ISSUE THREAD

**Issue by skyhhjmk** [2331892928/AMEN-GoEdge-User_frontEnd#4]
![image](https://github.com/2331892928/AMEN-GoEdge-User_frontEnd/assets/78078552/d31698c9-2556-4d25-9218-d25126d44eaf)

大佬还有这个

实测下来`^~ /api/`,`^~ /api`,`/api/`均会报错404

以下配置报错405

![image](https://github.com/2331892928/AMEN-GoEdge-User_frontEnd/assets/78078552/07156ce9-6b04-4518-a4ca-11d57beb0aa6)
![image](https://github.com/2331892928/AMEN-GoEdge-User_frontEnd/assets/78078552/57085091-afca-49ec-8101-53bace2c7a0d)

```
location ^~ /api/* {
    proxy_pass http://127.0.0.1:1050; 
    proxy_set_header Host $host; 
    proxy_set_header X-Real-IP $remote_addr; 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    proxy_set_header REMOTE-HOST $remote_addr; 
    proxy_set_header Upgrade $http_upgrade; 
    proxy_set_header Connection "upgrade"; 
    proxy_set_header X-Forwarded-Proto $scheme; 
    proxy_http_version 1.1; 
    add_header Cache-Control no-cache; 
}
```

**Comment by skyhhjmk** [comment]
![image](https://github.com/2331892928/AMEN-GoEdge-User_frontEnd/assets/78078552/a7f56108-52fd-4f8f-a960-31de0b102e8b)

**Comment by 2331892928** [comment]
后端代理错误，导致无法连接后端

**Comment by 2331892928** [comment]
但是你的后端正常工作，你可以重新设置代理

**Comment by 2331892928** [comment]
你尝试把routerConfig文件里'/api' 改为 '' 或'/'再去设置代理

**Comment by skyhhjmk** [comment]
当改为“/”时
![image](https://github.com/2331892928/AMEN-GoEdge-User_frontEnd/assets/78078552/c1d32003-5e6d-4ef4-9608-7f6406ab52fd)
![image](https://github.com/2331892928/AMEN-GoEdge-User_frontEnd/assets/78078552/6ecdd640-3384-41e6-b762-9d1a3aec20eb)
![image](https://github.com/2331892928/AMEN-GoEdge-User_frontEnd/assets/78078552/53d1f970-58c1-4792-be35-8a41719b2fca)
并且提示网络错误

```
location ^~ /api {
    proxy_pass http://127.0.0.1:1050; 
    proxy_set_header Host $host; 
    proxy_set_header X-Real-IP $remote_addr; 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    proxy_set_header REMOTE-HOST $remote_addr; 
    proxy_set_header Upgrade $http_upgrade; 
    proxy_set_header Connection "upgrade"; 
    proxy_set_header X-Forwarded-Proto $scheme; 
    proxy_http_version 1.1; 
    add_header Cache-Control no-cache; 
}
```

所有反代配置可能均已尝试，均报错“网络异常”
![image](https://github.com/2331892928/AMEN-GoEdge-User_frontEnd/assets/78078552/40fd4d66-33b8-49e3-a1e0-1b4164d14122)

**Comment by 2331892928** [comment]
改为 '' 了吗？

**Comment by skyhhjmk** [comment]
空值的还在测试

**Comment by skyhhjmk** [comment]
如果是空值的话，那么所有的反代组合下都会报错“请求方式不允许”

**Comment by 2331892928** [comment]
改为 ‘/api’
然后后端代理为/api/*
多试试

**Comment by 2331892928** [comment]
如还是不行可加我解决后远程，然后此issues由我来写解决方法。昵称就是我的Q

**Comment by skyhhjmk** [comment]
还是不行，qq加你了
