### ISSUE TITLE
添加证书时报错TypeError: this.certData.then is not a function

### ISSUE THREAD

**Issue by ning0818** [2331892928/AMEN-GoEdge-User_frontEnd#5]
![image](https://github.com/2331892928/AMEN-GoEdge-User_frontEnd/assets/117955401/dc27257c-98d5-4ae6-b3d9-af1f7f915353)
地址https://cdn.teamoo.club/certMain/cert
可以提供云端环境（宝塔）

**Comment by ning0818** [comment]
@2331892928

**Comment by 2331892928** [comment]
已解决，是使用者证书未上传就点击了添加
